// Code generated by gromer. DO NOT EDIT.
package main

import (
	"os"

	"github.com/gorilla/mux"
	"github.com/pyros2097/gromer"
	"github.com/rs/zerolog/log"
	"gocloud.dev/server"

	"pyros.sh/assets"
	"pyros.sh/components"
	"pyros.sh/pages/404"
	"pyros.sh/pages"
	"pyros.sh/pages/blog"
	"pyros.sh/pages/blog/_id_"
	"pyros.sh/pages/ref"
	"pyros.sh/pages/work"
	
)

func init() {
	gromer.RegisterComponent(components.Header)
	gromer.RegisterComponent(components.Layout)
	gromer.RegisterComponent(components.Page)
	gromer.RegisterComponent(components.Slider)
	
}

func main() {
	port := os.Getenv("PORT")
	r := mux.NewRouter()
	r.Use(gromer.CorsMiddleware)
	r.Use(gromer.LogMiddleware)
	
	r.NotFoundHandler = gromer.StatusHandler(not_found_404.GET)
	
	gromer.Static(r, "/assets/", assets.FS)
	gromer.Handle(r, "GET", "/api", gromer.ApiExplorer)
	gromer.Handle(r, "GET", "/", pages.GET)
	gromer.Handle(r, "GET", "/blog", blog.GET)
	gromer.Handle(r, "GET", "/blog/{id}", blog_id_.GET)
	gromer.Handle(r, "GET", "/ref", ref.GET)
	gromer.Handle(r, "GET", "/work", work.GET)
	
	log.Info().Msg("http server listening on http://localhost:"+port)
	srv := server.New(r, nil)
	if err := srv.ListenAndServe(":"+port); err != nil {
		log.Fatal().Stack().Err(err).Msg("failed to listen")
	}
}
