// Code generated by gromer. DO NOT EDIT.
package main

import (
	"github.com/gorilla/mux"
	"github.com/pyros2097/gromer"
	"github.com/rs/zerolog/log"
	"gocloud.dev/server"

	"pyros.sh/assets"
	"pyros.sh/components"
	"pyros.sh/pages/404"
	"pyros.sh/pages"
	"pyros.sh/pages/blog"
	"pyros.sh/pages/blog/_id_"
	"pyros.sh/pages/ref"
	"pyros.sh/pages/work"
	
)

func init() {
	gromer.RegisterComponent(components.RefHeader)
	gromer.RegisterComponent(components.Header)
	gromer.RegisterComponent(components.Layout)
	gromer.RegisterComponent(components.Page)
	gromer.RegisterComponent(components.Slider)
	gromer.RegisterComponent(components.Tag)
	
}

func main() {
	baseRouter := mux.NewRouter()
	baseRouter.Use(gromer.LogMiddleware)
	
	baseRouter.NotFoundHandler = gromer.StatusHandler(not_found_404.GET)
	
	staticRouter := baseRouter.NewRoute().Subrouter()
	staticRouter.Use(gromer.CacheMiddleware)
	gromer.StaticRoute(staticRouter, "/assets/", assets.FS)
	gromer.StylesRoute(staticRouter, "/styles.css")

	pageRouter := baseRouter.NewRoute().Subrouter()
	gromer.ApiExplorerRoute(pageRouter, "/explorer")
	gromer.Handle(pageRouter, "GET", "/", pages.GET)
	gromer.Handle(pageRouter, "GET", "/blog", blog.GET)
	gromer.Handle(pageRouter, "GET", "/blog/{id}", blog_id_.GET)
	gromer.Handle(pageRouter, "GET", "/ref", ref.GET)
	gromer.Handle(pageRouter, "GET", "/work", work.GET)
	

	apiRouter := baseRouter.NewRoute().Subrouter()
	apiRouter.Use(gromer.CorsMiddleware)
	
	
	
	log.Info().Msg("http server listening on http://localhost:3000")
	srv := server.New(baseRouter, nil)
	if err := srv.ListenAndServe(":3000"); err != nil {
		log.Fatal().Stack().Err(err).Msg("failed to listen")
	}
}
